### PR TITLE
add file hello

### PR DESCRIPTION
**Pull request by VolodymyrShabanov**

### CODE REVIEW

**Review by TheKirrrra — APPROVED** [review]

**Review by DmitriiSagaiko — CHANGES_REQUESTED** [review]
too much files in .idea.

**Review by MaximSakovich — APPROVED** [review]
ок

**Review by AndrewMiliy — APPROVED** [review]

**Review by TheKirrrra — APPROVED** [review]

**Comment by Mihail-Ned** [comment]
gut

**Review by DmitriiSagaiko — APPROVED** [review]
good !

**Review by aidinmaxim — APPROVED** [review]

**Review by Mihail-Ned — COMMENTED** [review]
gut

**Review by Mihail-Ned — APPROVED** [review]
gut

**Pull request merged**
